<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable> <!-- prevents it from being published as NuGet package -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFrameworks>$(NetFrameworkTestVersion);$(NetTestVersion);$(NetCoreTestVersion)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFrameworks>$(NetTestVersion);$(NetCoreTestVersion)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hyperion.Tests.FSharpData\Hyperion.Tests.FSharpData.fsproj" />
    <ProjectReference Include="..\Hyperion\Hyperion.csproj" />
  </ItemGroup>

</Project>
