# Pull request validation for Windows against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master ] # branch names which will trigger a build

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'windows_pr'
      displayName: 'Windows PR Validation'
      vmImage: 'windows-2019'
      scriptFileName: build.cmd
      scriptArgs: all
      
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'linux_pr_net_core'
      displayName: 'Linux PR Validation (netcoreapp3.1)'
      vmImage: 'ubuntu-16.04'
      scriptFileName: ./build.sh
      scriptArgs: runTestsNetCore
      
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'linux_pr_net_5'
      displayName: 'Linux PR Validation (net5.0)'
      vmImage: 'ubuntu-16.04'
      scriptFileName: ./build.sh
      scriptArgs: runTestsNet
